### ISSUE TITLE
Items are deleted if a printer is spammed fast enough

### ISSUE THREAD

**Issue by Hlebuw3k** [FelixVolo/ActuallyFaster#10]
I spammed a printer with an autoclicker and like all of my items got yeeted (I had 99 scrap and got like 20 items from all that)

**Comment by Hlebuw3k** [comment]
Currently I'll have to use the other mod for faster printers and interactibles, because it does not have this issue, Exchange Changes: https://thunderstore.io/package/Flyingcomputer/Exchange_Changes/

**Comment by FelixVolo** [comment]
Seems like the mod used a higher delay. I increased it in my new release to 0.3f :) please tell me if it works

**Comment by FelixVolo** [comment]
Okay it may have swallod some items and it made it even worse.... I'll update later again

**Comment by Hlebuw3k** [comment]
That definitely made it worse. Here is a quick test I did by cheating in scrap: https://youtu.be/WozzZpW4xG4
It consumes all items until I stop spamming it, then prints out only one, which should not happen

**Comment by FelixVolo** [comment]
> That definitely made it worse. Here is a quick test I did by cheating in scrap: https://youtu.be/WozzZpW4xG4 It consumes all items until I stop spamming it, then prints out only one, which should not happen

The same behaviour i discovered. I use the same values now as the mentioned mod and update again....

**Comment by FelixVolo** [comment]
Updated rn. I tested it with Aerolt and an autoclicker this time. Had it set to 0ms, 31 white scrap, let it run and no item lost.

**Comment by Hlebuw3k** [comment]
Works properly now, awesome!
