### ISSUE TITLE
mod does not work with mod manager

### ISSUE THREAD

**Issue by TurboNeon** [FelixVolo/ActuallyFaster#5]
the mod wont work when i load it with r2modman, do i need to do somthing else to make it work?
i use version 1.0.8

**Comment by FelixVolo** [comment]
This is a common problem from the Mod Manager. Please go to the modmanager, select ROR2 then go to Settings and click on "Browse profile folder".

Go to BepInEx -> plugins -> Felda-Actually_Faster and check if the ActuallyFaster.dll isn't called ActuallyFaster.dll.old or something.

**Comment by TurboNeon** [comment]
tnx bro i fixed it, i had i had r2api as a missing dependency
now its working

**Comment by TurboNeon** [comment]
its working
