### ISSUE TITLE
It's difficult to open a chest next to a shrine

### ISSUE THREAD

**Issue by bonjorno7** [FelixVolo/ActuallyFaster#6]
I just want to get some items from a multishop, not start the shrine of combat that's next to it.

**Comment by FelixVolo** [comment]
I can guarantee that my mod doesn't change the hitbox of objects.

**Comment by FelixVolo** [comment]
May you send me a video of it?

**Comment by bonjorno7** [comment]
Sorry for the late reply, I didn't see.
It only happens when they're right next to each other; holding use will trigger the closer one first, then the one behind it.
I'll record a video next time it happens.
