### ISSUE TITLE
Mod broke with v1.2.3

### ISSUE THREAD

**Issue by brianjliu** [FelixVolo/ActuallyFaster#7]
Print spamming now results in items being "destroyed." Printer takes regular amount of time to present item while still being able to accept items.

**Comment by FelixVolo** [comment]
This error occured once for another person when you use the mod WolfoQualityOfLife. Please turn off faster interactibles in WolfoQualityOfLife.cfg.

Orherwise the mod works perfectly with the newest version of ror 2. Can you please give me further details?

Which mods are you using?
Are you playing on a dedicated server or not?

**Comment by brianjliu** [comment]
Disabling the setting in WolfoQualityOfLife fixed it. I was unaware this was a setting with that mod.
